/**
 * The status pages' static assets, resolved from whichever source this build
 * has.
 *
 * Three sources, in priority order:
 *
 *  1. **A web directory on disk** — `dist/web`, next to the compiled JS. This
 *     is the tsup / `bun run src/cli.ts` path, unchanged from before: a
 *     developer who runs `npm run build:web` sees their change immediately,
 *     without regenerating a manifest. A compiled binary never has one.
 *  2. **The embedded manifest** (`webManifest.generated.json`). The only source
 *     that works inside a `bun build --compile` executable: Bun's standalone
 *     filesystem exposes embedded *files* but has no **directories**, so
 *     `existsSync('/$bunfs/root/web')` is false and `readdirSync` throws. A
 *     JSON module is inlined by the bundler, needs no filesystem at all, and
 *     behaves identically in every runtime.
 *  3. Nothing — the caller renders the built-in fallback shell.
 *
 * The manifest is generated by `scripts/build-web-manifest.mjs` and committed;
 * regenerate it (`npm run build:web`) after changing anything under `web/`.
 */
import { readFileSync, statSync } from 'fs';
import { join, normalize, sep } from 'path';
import { createHash } from 'crypto';
import generated from './webManifest.generated.json';

export interface WebAsset {
  /** Request path, always starting with `/`. */
  path: string;
  body: Buffer;
  contentType: string;
  /** Strong ETag, quoted, derived from the content. */
  etag: string;
  /** Content-addressed (hashed filename) — safe to cache for a year. */
  immutable: boolean;
}

interface ManifestEntry {
  contentType: string;
  encoding: string;
  etag: string;
  bytes: number;
  content: string;
}

const manifest = generated.files as Record<string, ManifestEntry>;
const manifestPaths = Object.keys(manifest);

/** Decoded bodies, kept so a page view is not a base64 decode per request. */
const decoded = new Map<string, Buffer>();

/**
 * Vite emits content-hashed filenames under `/assets/`. Only those get the
 * immutable, year-long cache — `index.html` must never be cached that way or a
 * deploy is invisible until the browser gives up.
 */
function isImmutable(path: string): boolean {
  return path.startsWith('/assets/');
}

function fromManifest(path: string): WebAsset | null {
  const entry = manifest[path];
  if (!entry) return null;

  let body = decoded.get(path);
  if (!body) {
    body = Buffer.from(entry.content, entry.encoding === 'base64' ? 'base64' : 'utf8');
    decoded.set(path, body);
  }

  return { path, body, contentType: entry.contentType, etag: entry.etag, immutable: isImmutable(path) };
}

// ---------------------------------------------------------------------------
// Directory fallback (source checkouts / tsup builds)
// ---------------------------------------------------------------------------

const CONTENT_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.webmanifest': 'application/manifest+json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.eot': 'application/vnd.ms-fontobject',
};

function contentTypeFor(path: string): string {
  const dot = path.lastIndexOf('.');
  return (dot === -1 ? undefined : CONTENT_TYPES[path.slice(dot).toLowerCase()]) ?? 'application/octet-stream';
}

/** Reject anything that could escape the web root before it reaches the disk. */
function safeRelative(path: string): string | null {
  if (!path.startsWith('/') || path.includes('\0')) return null;
  const normalised = normalize(path).replace(/^[/\\]+/, '');
  if (normalised === '' || normalised.startsWith('..') || normalised.split(/[/\\]/).includes('..')) return null;
  return normalised.split('/').join(sep);
}

function fromDirectory(dir: string | null, path: string): WebAsset | null {
  if (!dir) return null;
  const relative = safeRelative(path);
  if (!relative) return null;

  const file = join(dir, relative);
  try {
    if (!statSync(file).isFile()) return null;
  } catch {
    return null;
  }

  const body = readFileSync(file);
  return {
    path,
    body,
    contentType: contentTypeFor(path),
    etag: `"${createHash('sha256').update(body).digest('hex').slice(0, 32)}"`,
    immutable: isImmutable(path),
  };
}

// ---------------------------------------------------------------------------
// Public surface
// ---------------------------------------------------------------------------

export type WebAssetSource = 'embedded' | 'directory' | 'none';

export interface WebAssets {
  source: WebAssetSource;
  /** How many assets are available (embedded builds only; 0 for a directory). */
  count: number;
  /** Human-readable origin, for the startup log line. */
  origin: string;
  /** Resolve a request path, or `null` when this build cannot serve it. */
  get(path: string): WebAsset | null;
  /** The SPA shell, served for every HTML route. */
  index(): WebAsset | null;
}

/**
 * `candidateDirs` are on-disk web roots to try, most specific first. The first
 * one containing an `index.html` wins; only when none does — which is always
 * the case inside a compiled binary — does the embedded manifest take over.
 * Directory first so the existing tsup/`dist/web` behaviour is untouched and a
 * local `npm run build:web` shows up without regenerating the manifest.
 */
export function resolveWebAssets(candidateDirs: (string | null | undefined)[]): WebAssets {
  for (const candidate of candidateDirs) {
    if (!candidate) continue;
    let usable = false;
    try {
      usable = statSync(join(candidate, 'index.html')).isFile();
    } catch {
      usable = false;
    }
    if (!usable) continue;
    const dir = candidate;
    return {
      source: 'directory',
      count: 0,
      origin: dir,
      get: (path) => fromDirectory(dir, path),
      index: () => fromDirectory(dir, '/index.html'),
    };
  }

  if (manifestPaths.length > 0) {
    return {
      source: 'embedded',
      count: manifestPaths.length,
      origin: 'embedded manifest',
      get: (path) => fromManifest(path),
      index: () => fromManifest('/index.html'),
    };
  }

  return {
    source: 'none',
    count: 0,
    origin: 'none',
    get: () => null,
    index: () => null,
  };
}
